apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: hello-world
spec:
  schedule: "* * * * *"
  timezone: "America/Los_Angeles"
  concurrencyPolicy: "Replace"
  startingDeadlineSeconds: 0
  successfulJobsHistoryLimit: 4
  failedJobsHistoryLimit: 4
  suspend: false
  workflowSpec:
    entrypoint: hello-world
    templates:
      - name: hello-world
        container:
          image: hello-world
          command: ["echo"]
          args: ["Hello, World! Scheduled on: {{workflow.scheduledTime}}"]